[tool.poetry]
name = "nornir_napalm"
version = "0.1.0"
description = "NAPALM's plugins for nornir"
authors = ["David Barroso <dbarrosop@dravetech.com>"]
license = "Apache-2.0"

[tool.poetry.plugins."nornir.plugins.connections"]
"napalm" = "nornir_napalm.connections:Napalm"

[tool.poetry.dependencies]
python = "^3.6"
napalm = "^2"
nornir = { git = "https://github.com/nornir-automation/nornir/", branch = "3.0.0-entrypoints" }

[tool.poetry.dev-dependencies]
black = { version = "19.10b0", allow-prereleases = true }
mypy = "*"
pylama = "^7.7.1"
pytest = "*"
pytest-coverage = "^0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
